#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Wed Jul 14 17:09:21 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from MyFrame import MyFrame


class MyApp(wx.App):
				def OnInit(self):
								self.frame = MyFrame(None, wx.ID_ANY, "")
								self.SetTopWindow(self.frame)
								self.frame.Show()
								return True

# end of class MyApp

if __name__ == "__main__":
				gettext.install("app") # replace with the appropriate catalog name

				app = MyApp(0)
				app.MainLoop()
