# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Wed Jul 14 17:09:21 2021
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
				def __init__(self, *args, **kwds):
								# begin wxGlade: MyFrame.__init__
								kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
								wx.Frame.__init__(self, *args, **kwds)
								self.SetSize((1305, 758))
								self.SetTitle(_("frame"))

								# Menu Bar
								self.frame_menubar = wx.MenuBar()
								wxglade_tmp_menu = wx.Menu()
								self.frame_menubar.Append(wxglade_tmp_menu, _("File"))
								self.SetMenuBar(self.frame_menubar)
								# Menu Bar end

								self.frame_statusbar = self.CreateStatusBar(1)
								self.frame_statusbar.SetStatusWidths([-1])
								# statusbar fields
								frame_statusbar_fields = [_("frame_statusbar")]
								for i in range(len(frame_statusbar_fields)):
												self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

								# Tool Bar
								self.frame_toolbar = wx.ToolBar(self, -1)
								self.SetToolBar(self.frame_toolbar)
								self.frame_toolbar.Realize()
								# Tool Bar end

								sizer_9 = wx.BoxSizer(wx.HORIZONTAL)

								self.panel_5 = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
								self.panel_5.SetMinSize((300, 500))
								self.panel_5.SetScrollRate(10, 10)
								sizer_9.Add(self.panel_5, 1, wx.ALL | wx.EXPAND, 10)

								sizer_11 = wx.BoxSizer(wx.HORIZONTAL)

								bitmap_1 = wx.StaticBitmap(self.panel_5, wx.ID_ANY, wx.Bitmap("tmp/tmp0001.png", wx.BITMAP_TYPE_ANY))
								sizer_11.Add(bitmap_1, 0, 0, 0)

								self.panel_6 = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
								self.panel_6.SetMinSize((200, 600))
								self.panel_6.SetScrollRate(10, 10)
								sizer_9.Add(self.panel_6, 1, wx.ALL | wx.EXPAND, 5)

								sizer_12 = wx.BoxSizer(wx.VERTICAL)

								grid_sizer_2 = wx.BoxSizer(wx.VERTICAL)
								sizer_12.Add(grid_sizer_2, 0, wx.EXPAND, 0)

								self.button_1 = wx.Button(self.panel_6, wx.ID_ANY, _("button_1"))
								grid_sizer_2.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

								self.gauge_1 = wx.Gauge(self.panel_6, wx.ID_ANY, 10, style=0)
								grid_sizer_2.Add(self.gauge_1, 0, wx.ALL | wx.EXPAND, 5)

								self.window_1 = wx.SplitterWindow(self.panel_6, wx.ID_ANY)
								self.window_1.SetMinimumPaneSize(20)
								sizer_12.Add(self.window_1, 4, wx.ALL | wx.EXPAND, 10)

								self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)

								sizer_13 = wx.BoxSizer(wx.HORIZONTAL)

								self.list_ctrl_2 = wx.ListCtrl(self.window_1_pane_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
								self.list_ctrl_2.AppendColumn(_("A"), format=wx.LIST_FORMAT_LEFT, width=-1)
								self.list_ctrl_2.AppendColumn(_("B"), format=wx.LIST_FORMAT_LEFT, width=-1)
								self.list_ctrl_2.AppendColumn(_("C"), format=wx.LIST_FORMAT_LEFT, width=-1)
								sizer_13.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)

								self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

								sizer_14 = wx.BoxSizer(wx.HORIZONTAL)

								self.list_ctrl_3 = wx.ListCtrl(self.window_1_pane_2, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
								self.list_ctrl_3.AppendColumn(_("A"), format=wx.LIST_FORMAT_LEFT, width=-1)
								self.list_ctrl_3.AppendColumn(_("B"), format=wx.LIST_FORMAT_LEFT, width=-1)
								self.list_ctrl_3.AppendColumn(_("C"), format=wx.LIST_FORMAT_LEFT, width=-1)
								sizer_14.Add(self.list_ctrl_3, 1, wx.EXPAND, 0)

								self.panel_7 = wx.Panel(self.panel_6, wx.ID_ANY)
								sizer_12.Add(self.panel_7, 2, wx.EXPAND, 0)

								grid_sizer_1 = wx.GridSizer(3, 3, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								grid_sizer_1.Add((0, 0), 0, 0, 0)

								sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
								sizer_12.Add(sizer_15, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

								self.text_ctrl_1 = wx.TextCtrl(self.panel_6, wx.ID_ANY, "")
								sizer_15.Add(self.text_ctrl_1, 5, 0, 0)

								self.button_2 = wx.Button(self.panel_6, wx.ID_ANY, _("button_2"))
								sizer_15.Add(self.button_2, 1, 0, 0)

								self.panel_7.SetSizer(grid_sizer_1)

								self.window_1_pane_2.SetSizer(sizer_14)

								self.window_1_pane_1.SetSizer(sizer_13)

								self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)

								self.panel_6.SetSizer(sizer_12)

								self.panel_5.SetSizer(sizer_11)

								self.SetSizer(sizer_9)
								sizer_9.SetSizeHints(self)

								self.Layout()
								self.Centre()
								# end wxGlade

# end of class MyFrame
